In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [3]:
games = pd.read_csv("../data/raw/Video_Games_Sales_as_at_22_Dec_2016.csv")

In [4]:
games_clean = games.copy()

In [5]:
games_clean.shape

(16719, 16)

In [6]:
games_clean.isnull().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [7]:
games_clean[games_clean['Name'].isnull()]

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
659,NaN,GEN,1993.0,NaN,Acclaim Entertainment,1.78,0.53,0.00,0.08,2.39,NaN,NaN,NaN,NaN,NaN,NaN
14246,NaN,GEN,1993.0,NaN,Acclaim Entertainment,0.00,0.00,0.03,0.00,0.03,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
games_clean = games_clean.dropna(subset=['Name'])

In [9]:
games_clean.shape

(16717, 16)

In [10]:
games_clean['Name'].isnull().sum()

np.int64(0)

In [11]:
games_clean[games_clean['Genre'].isnull()]

Empty DataFrame
Columns: [Name, Platform, Year_of_Release, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales, Critic_Score, Critic_Count, User_Score, User_Count, Developer, Rating]
Index: []

In [12]:
games_clean[games_clean['Year_of_Release'].isnull()].head(10)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
183,Madden NFL 2004,PS2,NaN,Sports,Electronic Arts,4.26,0.26,0.01,0.71,5.23,94.0,29.0,8.5,140.0,EA Tiburon,E
377,FIFA Soccer 2004,PS2,NaN,Sports,Electronic Arts,0.59,2.36,0.04,0.51,3.49,84.0,20.0,6.4,76.0,EA Canada,E
456,LEGO Batman: The Videogame,Wii,NaN,Action,Warner Bros. Interactive Entertainment,1.80,0.97,0.00,0.29,3.06,74.0,17.0,7.9,22.0,Traveller's Tales,E10+
475,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,NaN,1.57,1.02,0.00,0.41,3.00,NaN,NaN,NaN,NaN,NaN,NaN
609,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.00,0.03,2.53,NaN,NaN,NaN,NaN,NaN,NaN
627,Rock Band,X360,NaN,Misc,Electronic Arts,1.93,0.33,0.00,0.21,2.47,92.0,72.0,8.2,178.0,Harmonix Music Systems,T
657,Frogger's Adventures: Temple of the Frog,GBA,NaN,Adventure,Konami Digital Entertainment,2.15,0.18,0.00,0.07,2.39,73.0,4.0,tbd,NaN,Konami Computer Entertainment Hawaii,E
678,LEGO Indiana Jones: The Original Adventures,Wii,NaN,Action,LucasArts,1.51,0.61,0.00,0.21,2.34,78.0,22.0,6.6,28.0,Traveller's Tales,E10+
719,Call of Duty 3,Wii,NaN,Shooter,Activision,1.17,0.84,0.00,0.23,2.24,69.0,42.0,6.7,61.0,Exakt,T
805,Rock Band,Wii,NaN,Misc,MTV Games,1.33,0.56,0.00,0.20,2.08,80.0,21.0,6.3,37.0,Harmonix Music Systems,T

In [13]:
games_clean['Year_of_Release'].value_counts().sort_index()

Year_of_Release
1980.0       9
1981.0      46
1982.0      36
1983.0      17
1984.0      14
1985.0      14
1986.0      21
1987.0      16
1988.0      15
1989.0      17
1990.0      16
1991.0      41
1992.0      43
1993.0      60
1994.0     121
1995.0     219
1996.0     263
1997.0     289
1998.0     379
1999.0     338
2000.0     350
2001.0     482
2002.0     829
2003.0     775
2004.0     762
2005.0     939
2006.0    1006
2007.0    1197
2008.0    1427
2009.0    1426
2010.0    1255
2011.0    1136
2012.0     653
2013.0     544
2014.0     581
2015.0     606
2016.0     502
2017.0       3
2020.0       1
Name: count, dtype: int64

In [14]:
games_clean['User_Score'].value_counts().head(10)

User_Score
tbd    2425
7.8     324
8       290
8.2     282
8.3     254
8.5     253
7.5     251
7.9     249
8.1     244
7.7     240
Name: count, dtype: int64

In [15]:
(games_clean['User_Score'] == 'tbd').sum()

np.int64(2425)

In [16]:
games_clean['User_Score'] = games_clean['User_Score'].replace('tbd', np.nan)

In [17]:
games_clean['User_Score'] = pd.to_numeric(games_clean['User_Score'])

In [18]:
games_clean['User_Score'].dtype

dtype('float64')

In [19]:
games_clean['User_Score'].isnull().sum()

np.int64(9127)

In [20]:
games_clean['User_Score'].describe()

count    7590.000000
mean        7.125046
std         1.500006
min         0.000000
25%         6.400000
50%         7.500000
75%         8.200000
max         9.700000
Name: User_Score, dtype: float64

In [21]:
games_clean[games_clean['Publisher'].isnull()]

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
475,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,NaN,1.57,1.02,0.00,0.41,3.00,NaN,NaN,NaN,NaN,NaN,NaN
1301,Triple Play 99,PS,NaN,Sports,NaN,0.81,0.55,0.00,0.10,1.46,NaN,NaN,NaN,NaN,NaN,NaN
1667,Shrek / Shrek 2 2-in-1 Gameboy Advance Video,GBA,2007.0,Misc,NaN,0.87,0.32,0.00,0.02,1.21,NaN,NaN,NaN,NaN,NaN,NaN
2212,Bentley's Hackpack,GBA,2005.0,Misc,NaN,0.67,0.25,0.00,0.02,0.93,NaN,NaN,NaN,NaN,NaN,NaN
3148,Nicktoons Collection: Game Boy Advance Video V...,GBA,2004.0,Misc,NaN,0.46,0.17,0.00,0.01,0.64,NaN,NaN,NaN,NaN,NaN,NaN
3159,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,Misc,NaN,0.46,0.17,0.00,0.01,0.64,NaN,NaN,NaN,NaN,NaN,NaN
3755,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,Misc,NaN,0.38,0.14,0.00,0.01,0.53,NaN,NaN,NaN,NaN,NaN,NaN
4127,Sonic the Hedgehog,PS3,NaN,Platform,NaN,0.00,0.48,0.00,0.00,0.48,43.0,17.0,4.1,176.0,Sonic Team,E10+
4508,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004.0,Misc,NaN,0.31,0.11,0.00,0.01,0.43,NaN,NaN,NaN,NaN,NaN,NaN
4615,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004.0,Misc,NaN,0.30,0.11,0.00,0.01,0.42,NaN,NaN,NaN,NaN,NaN,NaN
5294,Dragon Ball Z: Budokai Tenkaichi 2 (JP sales),Wii,NaN,Action,NaN,0.15,0.05,0.14,0.01,0.35,NaN,NaN,NaN,NaN,NaN,NaN
5633,Cartoon Network Collection: Game Boy Advance V...,GBA,2005.0,Misc,NaN,0.23,0.08,0.00,0.01,0.32,NaN,NaN,NaN,NaN,NaN,NaN
6256,The Legend of Zelda: The Minish Cap(weekly JP ...,GBA,NaN,Action,NaN,0.00,0.00,0.27,0.01,0.27,NaN,NaN,NaN,NaN,NaN,NaN
6415,Sonic X: Game Boy Advance Video Volume 1,GBA,2004.0,Misc,NaN,0.19,0.07,0.00,0.00,0.27,NaN,NaN,NaN,NaN,NaN,NaN
6532,Dora the Explorer: Game Boy Advance Video Volu...,GBA,2004.0,Misc,NaN,0.18,0.07,0.00,0.00,0.26,NaN,NaN,NaN,NaN,NaN,NaN
6626,Cartoon Network Collection: Game Boy Advance V...,GBA,2004.0,Misc,NaN,0.18,0.07,0.00,0.00,0.25,NaN,NaN,NaN,NaN,NaN,NaN
6831,All Grown Up!: Game Boy Advance Video Volume 1,GBA,2004.0,Misc,NaN,0.17,0.06,0.00,0.00,0.24,NaN,NaN,NaN,NaN,NaN,NaN
7189,Nicktoons Collection: Game Boy Advance Video V...,GBA,2004.0,Misc,NaN,0.16,0.06,0.00,0.00,0.22,NaN,NaN,NaN,NaN,NaN,NaN
7333,Yu Yu Hakusho: Dark Tournament,PS2,NaN,Fighting,NaN,0.10,0.08,0.00,0.03,0.21,56.0,15.0,8.5,18.0,Digital Fiction,T
7477,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,Misc,NaN,0.15,0.05,0.00,0.00,0.21,NaN,NaN,NaN,NaN,NaN,NaN
7930,Thomas the Tank Engine & Friends,GBA,2004.0,Adventure,NaN,0.13,0.05,0.00,0.00,0.19,NaN,NaN,NaN,NaN,NaN,NaN
8317,Dragon Ball GT: Game Boy Advance Video Volume 1,GBA,2004.0,Misc,NaN,0.12,0.05,0.00,0.00,0.17,NaN,NaN,NaN,NaN,NaN,NaN
8328,Codename: Kids Next Door: Game Boy Advance Vid...,GBA,2004.0,Misc,NaN,0.12,0.05,0.00,0.00,0.17,NaN,NaN,NaN,NaN,NaN,NaN
8358,Teenage Mutant Ninja Turtles: Game Boy Advance...,GBA,2004.0,Misc,NaN,0.12,0.04,0.00,0.00,0.17,NaN,NaN,NaN,NaN,NaN,NaN
8494,Stronghold 3,PC,2011.0,Strategy,NaN,0.06,0.10,0.00,0.00,0.16,47.0,29.0,3.0,350.0,FireFly Studios,T
8754,Cartoon Network Collection: Game Boy Advance V...,GBA,2005.0,Misc,NaN,0.11,0.04,0.00,0.00,0.15,NaN,NaN,NaN,NaN,NaN,NaN
8837,Pokémon: Johto Photo Finish: Game Boy Advance ...,GBA,2004.0,Misc,NaN,0.11,0.04,0.00,0.00,0.15,NaN,NaN,NaN,NaN,NaN,NaN
8883,Strawberry Shortcake: Game Boy Advance Video V...,GBA,2004.0,Misc,NaN,0.11,0.04,0.00,0.00,0.15,NaN,NaN,NaN,NaN,NaN,NaN
9511,Farming Simulator 2011,PC,2010.0,Simulation,NaN,0.00,0.13,0.00,0.00,0.13,NaN,NaN,7.0,23.0,Giants Software,E
9739,Super Robot Wars OG Saga: Masou Kishin II - Re...,PSP,NaN,Strategy,NaN,0.00,0.00,0.12,0.00,0.12,NaN,NaN,NaN,NaN,NaN,NaN
10378,Disney Channel Collection Vol. 1,GBA,2004.0,Misc,NaN,0.08,0.03,0.00,0.00,0.11,NaN,NaN,NaN,NaN,NaN,NaN
10487,Atsumare! Power Pro Kun no DS Koushien,DS,NaN,Sports,NaN,0.00,0.00,0.10,0.00,0.10,NaN,NaN,NaN,NaN,NaN,NaN
11093,Action Man-Operation Extreme,PS,NaN,Action,NaN,0.05,0.03,0.00,0.01,0.09,NaN,NaN,NaN,NaN,NaN,NaN
11546,Cartoon Network Collection: Game Boy Advance V...,GBA,2004.0,Misc,NaN,0.06,0.02,0.00,0.00,0.08,NaN,NaN,NaN,NaN,NaN,NaN
12525,Chou Soujuu Mecha MG,DS,NaN,Simulation,NaN,0.00,0.00,0.06,0.00,0.06,NaN,NaN,NaN,NaN,NaN,NaN
12569,Prinny: Can I Really Be The Hero? (US sales),PSP,NaN,Action,NaN,0.06,0.00,0.00,0.00,0.06,NaN,NaN,NaN,NaN,NaN,NaN
13318,Monster Hunter Frontier Online,PS3,NaN,Role-Playing,NaN,0.00,0.00,0.05,0.00,0.05,NaN,NaN,NaN,NaN,NaN,NaN
13712,B.L.U.E.: Legend of Water,PS,NaN,Adventure,NaN,0.00,0.00,0.04,0.00,0.04,NaN,NaN,NaN,NaN,NaN,NaN
14128,Housekeeping,DS,NaN,Action,NaN,0.00,0.00,0.04,0.00,0.04,NaN,NaN,NaN,NaN,NaN,NaN
14352,Bikkuriman Daijiten,DS,NaN,Misc,NaN,0.00,0.00,0.03,0.00,0.03,NaN,NaN,NaN,NaN,NaN,NaN
14687,World of Tanks,X360,NaN,Shooter,NaN,0.00,0.03,0.00,0.00,0.03,NaN,NaN,5.2,9.0,Microsoft Game Studios,NaN
14772,UK Truck Simulator,PC,2010.0,Simulation,NaN,0.00,0.03,0.00,0.00,0.03,NaN,NaN,NaN,NaN,NaN,NaN
15024,Umineko no Naku Koro ni San: Shinjitsu to Gens...,PS3,NaN,Adventure,NaN,0.00,0.00,0.02,0.00,0.02,NaN,NaN,NaN,NaN,NaN,NaN
15340,Mario Tennis,3DS,NaN,Sports,NaN,0.00,0.00,0.02,0.00,0.02,NaN,NaN,NaN,NaN,NaN,NaN
15417,Nicktoons Collection: Game Boy Advance Video V...,GBA,2005.0,Misc,NaN,0.01,0.01,0.00,0.00,0.02,NaN,NaN,NaN,NaN,NaN,NaN
15442,Demolition Company: Gold Edition,PC,2011.0,Simulation,NaN,0.00,0.02,0.00,0.00,0.02,NaN,NaN,NaN,NaN,Giants Software,NaN
15680,"Moshi, Kono Sekai ni Kami-sama ga Iru to suru ...",PSV,2016.0,Adventure,NaN,0.00,0.00,0.02,0.00,0.02,NaN,NaN,NaN,NaN,NaN,NaN
16019,Dream Dancer,DS,NaN,Misc,NaN,0.01,0.00,0.00,0.00,0.02,NaN,NaN,NaN,NaN,"CyberPlanet Interactive Public Co., Ltd.",E
16280,Homeworld Remastered Collection,PC,NaN,Strategy,NaN,0.00,0.01,0.00,0.00,0.01,86.0,49.0,8.2,324.0,Gearbox Software,E10+
16296,AKB1/48: Idol to Guam de Koishitara...,X360,NaN,Misc,NaN,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16306,Super Robot Monkey Team: Game Boy Advance Vide...,GBA,2005.0,Misc,NaN,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16332,Brothers in Arms: Furious 4,X360,NaN,Shooter,NaN,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,Gearbox Software,M
16339,Dance with Devils,PSV,2016.0,Action,NaN,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16662,Driving Simulator 2011,PC,2011.0,Racing,NaN,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
games_clean['Publisher'].isnull().sum()

np.int64(54)

In [23]:
games_clean.info()

<class 'pandas.DataFrame'>
Index: 16717 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  str
 1   Platform         16717 non-null  str
 2   Year_of_Release  16448 non-null  float64
 3   Genre            16717 non-null  str
 4   Publisher        16663 non-null  str
 5   NA_Sales         16717 non-null  float64
 6   EU_Sales         16717 non-null  float64
 7   JP_Sales         16717 non-null  float64
 8   Other_Sales      16717 non-null  float64
 9   Global_Sales     16717 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       7590 non-null   float64
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  str
 15  Rating           9950 non-null   str
dtypes: float64(10), str(6)
memory usage: 3.1 MB

In [24]:
games_clean.to_csv("../data/cleaned/video_games_sales_cleaned.csv", index=False)

In [25]:
games_clean["Year_of_Release"] = games_clean["Year_of_Release"].astype("Int64")
games_clean["Critic_Count"] = games_clean["Critic_Count"].astype("Int64")
games_clean["User_Count"] = games_clean["User_Count"].astype("Int64")

games_clean.to_csv(
    "../data/cleaned/video_games_sales_cleaned.csv",
    index=False,
    na_rep="NULL"
)